# GitHub Actions Workflow created for testing the application
name: Build

on:
  workflow_dispatch:
  push:

permissions:
  pull-requests: write

jobs:
  runTests:
    runs-on: ubuntu-latest
    steps:
      # Check out current repository
      - name: checkout
        uses: actions/checkout@v3

      # Setup Java environment for the next steps
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      # Start ssh-agent and set it to use the same ssh_auth_sock value.
      - name: Add the secret key to the SSH Agent
        env:
          SSH_PASSPHRASE: ${{secrets.SSH_PASSPHRASE}}
          SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          echo 'echo $SSH_PASSPHRASE' > ~/.ssh_askpass && chmod +x ~/.ssh_askpass
          echo "$SSH_PRIVATE_KEY" | tr -d '\r' | DISPLAY=None SSH_ASKPASS=~/.ssh_askpass ssh-add - >/dev/null
          echo "SSH_AUTH_SOCK=$SSH_AUTH_SOCK" >> $GITHUB_ENV
      # Run tests and build the application
      - name: build
        working-directory: './'
        run: |
          ./mvnw verify

      - name: AutoMerge Dependabot PRs
        if: success() && github.actor == 'dependabot[bot]' && github.ref != 'refs/heads/main'
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          GH_TOKEN: ${{secrets.CLASSIC_GH_TOKEN}}
        run: |
          echo "found successful dependabot PR, merging it"
          gh pr merge --merge --admin    
