# GitHub Actions Workflow created for testing the application
name: Build

on:
  workflow_dispatch:
  push:

permissions:
  pull-requests: write

jobs:
  runTests:
    runs-on: ubuntu-latest
    steps:
      # Check out current repository
      - name: checkout
        uses: actions/checkout@v3

      # Setup Java environment for the next steps
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      # setup local ssh-agent and add the radicle private key
      - name: Setup ssh-agent
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # Run tests and build the application
      - name: build
        working-directory: './'
        run: |
          ./mvnw verify

      - name: AutoMerge Dependabot PRs
        if: success() && github.actor == 'dependabot[bot]' && github.ref != 'refs/heads/main'
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          GH_TOKEN: ${{secrets.CLASSIC_GH_TOKEN}}
        run: |
          echo "found successful dependabot PR, merging it"
          gh pr merge --merge --admin    
