# GitHub Actions Workflow created for handling the release process based on the draft release prepared
# with the Draft Release workflow.

name: Release Docker Image
on:
  release:
    types: [prereleased, released]

jobs:
  releaseDockerImage:
    name: Release Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Pull Draft Docker Image
        if: success()
        env:
          IMAGE_NAME: ${{ github.repository }}
          IMAGE_VERSION: ${{ env.VERSION }}
          REGISTRY_PASS: ${{ secrets.GITHUB_TOKEN }}
          REGISTRY_USER: ${{ github.actor }}
          REGISTRY_NAME: ghcr.io
        run: |
          set -x
          # push image to github containers registry 
          echo $REGISTRY_PASS | docker login "${REGISTRY_NAME}" -u "${REGISTRY_PASS}" --password-stdin
          docker pull "${REGISTRY_NAME}/${IMAGE_NAME}:draft"
          docker tag "${REGISTRY_NAME}/${IMAGE_NAME}:draft" "${REGISTRY_NAME}/${IMAGE_NAME}:latest"
          docker push "${REGISTRY_NAME}/${IMAGE_NAME}:latest"
